name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code into the runner's filesystem
      - name: Checkout code
        uses: actions/checkout@v2

      # Your existing steps
      - name: tests
        run: |
          ls -all
          pip install -r requirements.txt
          pip install .
          pytest

      - name: linting
        run: |
          pip install flake8
          flake8 .
